version: '2'
services:
    rideshare-app:
        image: rideshare
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rideshare-mysql:3306/rideshare?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=rideshare-elasticsearch:9300
        ports:
            - 8080:8080
    rideshare-mysql:
        extends:
            file: mysql.yml
            service: rideshare-mysql
    rideshare-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rideshare-elasticsearch
